export const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
export const SEARCH_BLUR = 'header/SEARCH_BLUR'
export const HEADER_LIST = 'header/HEADER_LIST'
export const MOVE_ENTER = 'header/MOVE_ENTER'
export const MOVE_LEAVE = 'header/MOVE_LEAVE'
export const CHANGE_TITLE = 'header/CHANGE_TITLE'